name: span_builder
description: Facilitates creation of spans from plain text and provides automated disposal of GestureRecognizers
version: 0.2.0
homepage: https://github.com/eyeem/span_builder

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

